### ISSUE TITLE
Vendor screen modification

### ISSUE THREAD

**Issue by nvijaykarthik** [seyyonist/seyon-requirements#12]
Mandatory : Name, address line 1 , city , state, country.

GSTIN 1st 2digit should be equal to state code  number next 10 digits will be pan number, 
If GSTIN then Pan Number should come.
Status drop down should be added.
Load the head of account from dropdown.

Nature of account : Savings, Current, OD,OC ->  dropdown
Bank name 
SWIFT code.

**Comment by jrkrish82** [comment]
in progress

**Comment by jrkrish82** [comment]
done
