### ISSUE TITLE
Voucher screen modification

### ISSUE THREAD

**Issue by nvijaykarthik** [seyyonist/seyon-requirements#15]
Invoice date should not be greater than voucher date.
Head of account to drop down.
upload the invoice bill as image.
If GST is not entered in vendor screen , then GST fields should be disabled.
If pan number is not entered  then TDS amount should be disabled
CGST,SGST -> IGST - is either or.
new field Credit period *  number box
new field Payment due date * date .

new Avail input credit -> check box-> YES/NO : if GST fields are filled then allow to edit if no GST feilds are entered then disable the check box.

Deduction TDS -> check box -> Yes or no : if yes then either TDS amount or Others should be entered.
if it is no : then do not allow to select the Deductions..

**Comment by jrkrish82** [comment]
in progress

**Comment by jrkrish82** [comment]
realign the UI - next steps

**Comment by jrkrish82** [comment]
done...realign the UI - next steps - will be worked seperately
