### ISSUE TITLE
Vendor Master screen - new

### ISSUE THREAD

**Issue by jrkrish82** [seyyonist/seyon-requirements#6]
Vendor Name
Vendor Address
Vendor GST Details
Vendor PAN
Vendor Bank Details

**Comment by nvijaykarthik** [comment]
I will be exposing get vendor list for that particular company.
GET: /api/vendor

**Comment by nvijaykarthik** [comment]
Changes completed

**Comment by nvijaykarthik** [comment]
Merged to Master branch
