### ISSUE TITLE
Voucher Search

### ISSUE THREAD

**Issue by jrkrish82** [seyyonist/seyon-requirements#8]
Voucher search options needs to be added

**Comment by nvijaykarthik** [comment]
V. No | auto |   | V. Dt | auto |  
-- | -- | -- | -- | -- | --
Inv No. | Manual |   | Inv Dt | Manual |  
  |   |   |   |   |  
Vendor Name | Drop down |  
Head of A/c | Drop down |  
  |   |   |   |   |  
Amount Net |   |   | Deductions |   |  
CGST |   |   | TDS % |   |  
SGST |   |   | TDS Amount |   | B
IGST |   |   | Others |   | C
reimbursement |   |   | Amount due |   | A-B-C
Total | 0 | A |   |   |  
  |   |   |   |   |  
Particulars |   |   | Deductions Remarks |   |  
  |  
  |   |   |   |   |  
Save | Edit |   | Approve |   |

**Comment by nvijaykarthik** [comment]
Changes completed
